import { cn } from "@/lib/utils";

export type AiChatRole = "user" | "assistant";

/**
 * One turn in the AI Architect conversation.
 *
 * This is a **temporary, client-local** record: the ID is generated by the
 * panel for React's benefit alone, and nothing here reaches Liveblocks,
 * Presence, or PostgreSQL. A persisted conversation is a later unit.
 */
export interface AiChatMessage {
  id: string;
  role: AiChatRole;
  content: string;
}

interface AiChatMessageBubbleProps {
  message: AiChatMessage;
}

/**
 * A single message bubble.
 *
 * Both roles are drawn here although **only `user` messages exist yet** — the
 * assistant treatment is prepared for the unit that adds a model, so the two
 * sides of a conversation are described in one place rather than one of them
 * appearing later beside the other.
 *
 * A user message is right-aligned on the `--primary` surface, which is legible
 * against the dark panel; an assistant message is left-aligned on the elevated
 * `--popover` surface with a `--border` edge, so it reads as a card on the panel
 * rather than as a second accent.
 */
export function AiChatMessageBubble({ message }: AiChatMessageBubbleProps) {
  const isUserMessage = message.role === "user";

  return (
    <li className={cn("flex", isUserMessage ? "justify-end" : "justify-start")}>
      <div
        className={cn(
          "max-w-[85%] rounded-xl px-3 py-2 text-sm leading-relaxed whitespace-pre-wrap text-pretty",
          isUserMessage
            ? "bg-primary text-primary-foreground"
            : "border border-border bg-popover text-foreground"
        )}
      >
        {message.content}
      </div>
    </li>
  );
}
